version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1!
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root1!
    depends_on:
      - db
    networks:
      - my-network

  backup:
    image: mysql:8.0
    volumes:
      - ./sql:/backup:rw
    command: >
      bash -c "sleep 30; while true; do
        mysqldump -h db -u root -proot1! database > /backup/database.sql;
        sleep 60;
      done"


    depends_on:
      - db
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    external: true
